Do not silently skip tests having failing imports
Introduced in b36f8e3c6bad78a2d5814b7fdfa686e8d78f9c78

Use case:

you have a test module in myaddon/tests/test_feature.py In this test module,
you import a lib, such as: 'import vcr'.  You forget to install 'vcrpy' in your
environment.

The exception is:

ImportError: No module named 'vcr'

As a result, all the tests in the module are silently ignored, not failing nor
successful.

The original goal of this part of code was to ignore the import of the 'tests'
module inside the addon. This is the exception raised when an addon doesn't
contain a 'tests' directory:

ImportError: No module named 'odoo.addons.myaddon.tests'

This commit compares the full path to be sure we don't ignore the wrong
imports.